name: ict602_app
description: A Flutter application for ICT602 - Multi-level Login with Carry Mark Management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.0
  webview_flutter: 4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/
